### ISSUE TITLE
Query: does it supports latest security supported .NET core version?

### ISSUE THREAD

**Issue by poojashahms** [microsoft/azure-pipelines-coveragepublisher#49]
In my pipeline, I have started getting this message and hence want to move to supported version to .NET 7 or 6 as per https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core  
```/Users/runner/.dotnet/sdk/7.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/runner/CoveragePublisher/azure-pipelines-coveragepublisher/src/CoveragePublisher.Console/CoveragePublisher.Console.csproj::TargetFramework=netcoreapp2.1]```

The readme and yml both mentions .NET 2.0 https://github.com/microsoft/azure-pipelines-coveragepublisher#usage
https://github.com/microsoft/azure-pipelines-coveragepublisher/blob/a52b137cf7e94ae5103becd97332d4d1a7261de7/azure-pipelines.yml#L49

**Comment by vinayakmsft** [comment]
Upgraded the .net core to 7.0  to fix the issue.
