### ISSUE TITLE
Build started failing with: error NETSDK1031: specify RuntimeIdentifier or set SelfContained to false

### ISSUE THREAD

**Issue by poojashahms** [microsoft/azure-pipelines-coveragepublisher#53]
The commit updating the .NET version: https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/52/commits/68874da7beca059f794f23134eacae60ecea0626

It was working when the project was on netcoreapp3.1 and started failing to build anytime time 2 PM on 13th April, 2023

To try it out, I installed .NET 6 in my local and ran on it, but still the same error. 
<img width="1692" alt="Screenshot 2023-04-14 at 3 18 10 PM" src="https://user-images.githubusercontent.com/125377350/232010979-8aef109b-1c8d-4363-acb6-cd242c69b181.png">

**Possible solutions:**
- Move to .NET7  https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/54
- Set selfContained to false https://github.com/microsoft/azure-pipelines-coveragepublisher/pull/55
- Revert to prev netcore3.* until proper fix it found.

**Comment by poojashahms** [comment]
cc: @vinayakmsft

**Comment by vinayakmsft** [comment]
Upgraded .net core to 7.0 . Fixed the issue.
