### ISSUE TITLE
Publish code coverage results suddenly started failing: ReportGeneratorTool exception

### ISSUE THREAD

**Issue by josundt** [microsoft/azure-pipelines-coveragepublisher#80]
Suddenly all "Publish code coverage results task v2" in build pipelines started failing".
I have successfully been using v2 of this task with multiple pipelines with generated coverage.xml (MS CoverageXML) file for quite some time.

Last successful build pipeline: 
  * Task: Publish code coverage results v2
  * Version: **2.248.1** 

First failed pipeline:
  * Task: Publish code coverage results v2
  * Version: **2.248.3**

I looked at the last commits in this repository and it looks like a fix for this has been submitted in PR #79.
The line number in the stack trace from my failed pipeline logs below (ReportGeneratorTool.cs:line 63) is the same line number that got fixed in this PR (see below).

When will this fix be deployed to Azure DevOps?
I have to disable this until a fix has been deployed...

```bash
Starting: publish coverage report
==============================================================================
Task         : Publish code coverage results v2
Description  : Publish any of the code coverage results from a build
Version      : 2.248.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
==============================================================================
##[error]Error occured while parsing coverage files. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.Azure.Pipelines.CoveragePublisher.Parsers.ReportGeneratorTool.GetFileCoverageInfos() in D:\a\1\s\src\CoveragePublisher\Parsers\CoverageParserTools\ReportGeneratorTool.cs:line 63
   at Microsoft.Azure.Pipelines.CoveragePublisher.Parsers.Parser.GetFileCoverageInfos() in D:\a\1\s\src\CoveragePublisher\Parsers\Parser.cs:line 35
```

**Comment by josundt** [comment]
@vinayakmsft Any update on this? My build pipelines still need to temporarily disable this task 😕

**Comment by vinayakmsft** [comment]
The task version is rolled back to 2.248.1 where its not having the issue
